#!/bin/bash
source sideloader-config

while test $# -gt 0; do
  case "$1" in
    --askpackage)
      ASKPACKAGE=1
      shift
      ;;
    --packagename*)
      PACKAGENAME=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    --username*)
      NAME=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    *)
      break
      ;;
  esac
done


clearLog

deviceCheck



if [ $ASKPACKAGE ]; then
  while [ -z $PACKAGENAME ] && [ -z $CI ]; do
    PACKAGENAME=$(dialog --title "Packagename" --inputbox "Please enter a packagename:" 0 0 --output-fd 1)
  done
fi








if [ -z $PACKAGENAME ]; then
  [ -z $CI ] && OLDUSER=$($ADB shell settings get global username)
  ok "Current global username detected as \"$OLDUSER\""
fi

if [ ! -z $PACKAGENAME ]; then
  [ -z $CI ] && OLDUSER=$($ADB shell settings get global username_$PACKAGENAME)
  ok "$PACKAGENAME username detected as \"$OLDUSER\""
fi



while [ -z $NAME ] && [ -z $CI ]; do
  NAME=$(dialog --title "Username" --inputbox "Please enter a username" 0 0 --output-fd 1)
done




if [ -z $PACKAGENAME ]; then
  [ -z $CI ] && $ADB shell settings put global username $NAME
  [ -z $CI ] && $ADB shell "echo '{\"username\":\"$NAME\"}' > /sdcard/user.json"
  [ -z $CI ] && $ADB shell "echo '{\"username\":\"$NAME\"}' > /sdcard/qq1091481055.json"
  ok "Global username changed to \"$NAME\""
fi


if [ ! -z $PACKAGENAME ]; then
	[ -z $CI ] && $ADB shell settings put global username_$PACKAGENAME $NAME
	ok "$PACKAGENAME username changed to \"$NAME\""
fi


dialogLog