#!/bin/bash

source sideloader-config

if [ $# -eq 0 ]; then
  echo "No arguments supplied"
  exit
else
  PACKAGENAME=$1
fi


sideload-change-username
sideload-change-rate
sideload-change-res
if [[ "$APKNAME" == *"custom"* ]] || [[ "$APKNAME" == *"Custom"* ]]; then
  [ -z $CI ] && zenity --info --width=800 --text="We have detected that this might be a so called '90hzCustomRes' release!\nThe following settings may be ignored if this is not the case."
  sideload-change-username --packagename="$PACKAGENAME"
  sideload-change-rate --packagename="$PACKAGENAME"
  sideload-change-res --packagename="$PACKAGENAME"
fi


ok ""
ok ""
ok "DONE, install finished, you can now disconnect your device"
