#!/bin/bash

source sideloader-config

if [ $# -eq 0 ]; then
  echo "No arguments supplied"
  exit
else
  PACKAGENAME=$1
fi



#MP user stuff
[ -z $CI ] && OLDUSER=$($ADB shell settings get global username)


[ -z $CI ] && USERNAME=$(zenity --entry --entry-text="$OLDUSER"  --title="Username selection" --text="Please enter a multiplayer username below and press [ENTER].")

if [ ! -z $USERNAME ]; then

	[ -z $CI ] && $ADB shell settings put global username $USERNAME
	[ -z $CI ] && $ADB shell settings put global username_$PACKAGENAME $USERNAME
	[ -z $CI ] && $ADB shell "echo '{\"username\":\"$USERNAME\"}' > /sdcard/user.json"
	[ -z $CI ] && $ADB shell "echo '{\"username\":\"$USERNAME\"}' > /sdcard/qq1091481055.json"
	ok "Multiplayer username set as: $USERNAME"

fi
#end json and multiplayer user test



HZONE=FALSE
HZTWO=FALSE
[ -z $CI ] && [ "$($ADB shell getprop debug.oculus.refreshRate)" == "72" ] && HZONE=TRUE
[ -z $CI ] && [ "$($ADB shell getprop debug.oculus.refreshRate)" == "90" ] && HZTWO=TRUE
[ -z $CI ] && HZCHOICE=$(zenity --list --title="Global Hz selection" --text "Set device to 72Hz or 90Hz? (does not survive reboot)" --hide-header  --radiolist --column "Pick" --column "Choice" $HZONE "72" $HZTWO "90" )
if [ ! -z $HZCHOICE ]; then
	$ADB shell setprop debug.oculus.refreshRate "$HZCHOICE"
	ok "$HZCHOICE hz selected for hmd"
fi
#end 90hz

if [[ "$APKNAME" == *"custom"* ]] || [[ "$APKNAME" == *"Custom"* ]]; then

  [ -z $CI ] && zenity --info --width=800 --text="We have detected that this might be a so called '90hzCustomRes' release!\nThe following settings may be ignored if this is not the case."

  [ -z $CI ] && APKHZCHOICE=$(zenity --list --title="CustomRes APK Hz selection" --text "Please hoose an APK specific refresh rate for this CustomRes crack." --hide-header  --radiolist --column "Pick" --column "Choice" FALSE "72" FALSE "90" )
  if [ "$APKHZCHOICE" == "90" ]; then
    $ADB shell settings put global 90hz_$PACKAGENAME 1
    ok "$APKHZCHOICE hz selected for $PACKAGENAME"
  fi
  if [ "$APKHZCHOICE" == "72" ]; then
    $ADB shell settings put global 90hz_$PACKAGENAME 0
    ok "$APKHZCHOICE hz selected for $PACKAGENAME"
  fi


  [ -z $CI ] && APKRES=$(zenity --entry --entry-text="2536"  --title="CustomRes APK Resolution selection" --text="Please enter an APK specific resolution for this CustomRes crack.")
  if [ ! -z $APKRES ]; then
    [ -z $CI ] && $ADB shell settings put global texture_size_$PACKAGENAME $APKRES
    ok "Resolution $APKRES x $APKRES selected for $PACKAGENAME"
  fi

fi
#texture_size_

ok ""
ok ""
ok "DONE, install finished, you can now disconnect your device"
