#!/bin/bash
source sideloader-config
osCheck

clearLog
deviceCheck



if [[ $DEVICE == 192* ]]
then
  ok "Already connected via wifi."
  $ADB devices
  dialogLog
  exit 0
fi


info "Attempting to find the ip of your quest."
WIFIIP=$($ADB shell ip addr show wlan0 2> /dev/null | grep 'inet ' | cut -d' ' -f6|cut -d/ -f1 | sed '/^$/d') 2> /dev/null


if [ -z "$WIFIIP" ]
then
  error "Please connect your quest to the same wifi network as this computer."
  dialogLog
  exit 0
fi


info "Found the ip of your quest [$DEVICE]."

info "Attempting to change adb to TCPIP mode."
WIFISTART=$($ADB tcpip 5555 | tee /dev/tty)


info "Attempting to connect adb to [$WIFIIP] over TCPIP."
WIFICHECK=$($ADB connect $WIFIIP:5555 | tee /dev/tty)

if [ "$WIFICHECK" == "connected to $WIFIIP:5555" ]
then
  ok "ADB over WIFI established successfully [$WIFIIP]"
  ok "You may now unplug your cable"
  adb devices
  dialogLog
  exit 0
else
  error "ADB over WIFI could not be established.
  dialogLog"
  exit 1
fi

exit 0
