#!/bin/bash
echo "Checking latest version online"
VERSION=$(cat "$HOME/quest-sideloader-linux/sideloader-version.txt")
NEWVERSION=$(git ls-remote https://github.com/whitewhidow/quest-sideloader-linux.git  | grep "refs/heads/main" | cut -f 1)

if [[ "$NEWVERSION" != "$VERSION" ]]; then
  echo ''
  echo -e ' => YOU ARE NOT RUNNING THE LATEST STABLE VERSION\n    PLEASE TRY UPGRADING OF YOU EXPERIENCE ANY ISSUES (OR TRY THE LATEST DEV)'
  echo ''
else
  echo -ne ''
  #echo ' => YOU ARE RUNNING THE LATEST STABLE VERSION'
  #echo ''
fi


case "$OSTYPE" in
linux*) OSTYPE="linux" ;;
darwin*) OSTYPE="mac" ;;
*) echo "unknown OS: $OSTYPE DETECTED" && echo "please submit a ticket om github?" && sleep 30 && exit ;;
esac

if [[ $(which sideload) != *"sideload"* ]]; then
  echo ''
  echo 'Please globally install the sideloader first from https://github.com/whitewhidow/quest-sideloader-linux'
  echo ''
  read -p "Press enter to close"
  exit 1
fi


#echo "Checking zenity installation."
if [ -z $CI ] && [[ $(which zenity 2>/dev/null) != *"zenity"* ]]; then
  echo "Installing zenity."
  (sudo apt install zenity >/dev/null 2>/dev/null || brew install zenity >/dev/null 2>/dev/null) && echo "zenity installed."
else
  echo -ne ''
  #echo "Zenity installation found."
fi


SELECTION=$HOME
MOUNTSUCCESS=false
#check already mounted set $MOUNTSUCCESS
if [ "$(ls -A /tmp/mnt/ 2>/dev/null)" ]; then
  MOUNTSUCCESS=true
  SELECTION=/tmp/mnt
fi


# if not $MOUNTSUCCESS, ask
[ -z $CI ] && [[ $MOUNTSUCCESS == false ]]  && zenity --question --width=800 --text="Would you like to mount the drive directly? [!BETA!]"
if [ $? = 0 ] || [ ! -z $CI ]; then
  echo "Attempting to serve the mount, Please wait."
  SELECTION="/tmp/mnt/"

  nohup /usr/local/bin/whitewhidow-mount "/tmp/mnt" mount </dev/null >/dev/null 2>&1 &
  x=1
  while [ $x -le 10 ] && [[ $MOUNTSUCCESS == false ]] ; do
    echo "Checking if drive is mounted (attempt $x/10)"
    sleep 3
    x=$(($x + 1))
    if [ "$(ls -A $SELECTION)" ]; then
      MOUNTSUCCESS=true
    fi
  done

  if [ $OSTYPE == "mac" ]; then
    nohup /usr/local/bin/whitewhidow-mount "/tmp/mnt" cmount </dev/null >/dev/null 2>&1 &
    x=1
    echo "You are on OSX, we will retry with Cmount !"
    while [ $x -le 10 ] && [[ $MOUNTSUCCESS == false ]] ; do
      echo "Checking if drive is mounted (attempt $x/10)"
      sleep 3
      x=$(($x + 1))
      if [ "$(ls -A $SELECTION)" ]; then
        MOUNTSUCCESS=true
      fi
    done
  fi

  if [[ $MOUNTSUCCESS == true ]]; then
    [ -z $CI ] && zenity --info --text="\n\n Cloud is mounted at: $SELECTION ($(ls -A $SELECTION | wc -l) folders available)\n\n" --width="600"
  else
    [ ! -z $CI ] && echo "CI MOUNT FAILED" && exit 1
    SELECTION=$HOME
    ERRORTEXT="\nERROR\n\nThe mounting process encountered an issues, please provide the terminal output to \n<a href=\"https://github.com/whitewhidow/quest-sideloader-linux/issues\">https://github.com/whitewhidow/quest-sideloader-linux/issues</a>\n\nAnd i will gladly assist you!\n\n"
    ERRORTEXT+="\nYou can still use 'sideload-gui' to sideload apps you have manually downloaded\n\n"
    [ -z $CI ] && zenity --warning --text="$ERRORTEXT" --width="600"
  fi

fi

cd "$SELECTION"

[ ! -z $CI ] && cd /tmp/mnt && cd "$(ls -d */|head -n 1)" && /usr/local/bin/sideload

[ ! $MOUNTSUCCESS ] && EXTRALINE="Having_trouble_mounting_the_drive???"

while [ -z $CI ] && true; do


  globby="./*"

  if [ `ls -1A . | wc -l` -eq 0 ]; then
    cd ..
    SELECTION=$PWD
  fi

  SELECTION=$(zenity --list --title="Current dir: $PWD" --text="Please select to an APK file to sideload." \
    --ok-label "Select Folder/APK" --cancel-label "Close Sideloader" --extra-button "View available updates [BETA]"  \
    --width=800 --height=600 --column="Filename" $([ ! $MOUNTSUCCESS ] && echo -e "$EXTRALINE") "../ (Directory up)" ${globby} "../ (Directory up)" 2>/dev/null)
  CLEANFOLDER=$(echo "$SELECTION" | sed -e 's/\\/\\\\/g' -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g')

  #sleep 10
  #echo "SELECTED: $SELECTION\n\n"
  if [[ "$SELECTION" == *"available updates"* ]]; then
    [ -z $CI ] && [ $MOUNTSUCCESS ] && UPD=$(sideload-check-updates | tee /dev/tty | grep "[+]") ; zenity --info --width=800 --text="We found the following available updates:\n\n$UPD" ; continue 1
    [ ! $MOUNTSUCCESS ] &&  zenity --info --width=800 --text="\n\nSorry this feature only works when the mount is successfull, (obviously) "
  fi
  [[ "$SELECTION" == *"trouble_mounting"* ]] && zenity --info --width=800 --text="\n\nPlease contact me if you are experiencing issues mounting the drive.\n\nhttps://github.com/whitewhidow/quest-sideloader-linux/\nor\nhttps://t.me/whitewhidow\n\n" && continue

  [[ "$SELECTION" == "../"* ]] && cd ../ && continue
  [[ -z $SELECTION ]] && break
  [ $? -eq 0 ] && break



  if [[ "$SELECTION" == *".apk" ]]; then

    zenity --question --width=800 --text="Do you want to install the apk ($SELECTION) from the directory \"$PWD\" ?"
    if [ $? = 0 ]; then
      #echo '' > /tmp/sideload.log
      /usr/local/bin/sideload "$SELECTION" # | tee /tmp/sideload.log

      #RESULT=$(cat /tmp/sideload.log | sed -e 's/\\/\\\\/g' -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' | tr '' '\n' | tail -n +2)
      #zenity --info --width=800 --text="$(echo $RESULT| tr '' '\n' | tail -n +2)"
      ISSUETEXT="If any error has occured, please provide me with a copy of the terminal window response at \n<a href=\"https://github.com/whitewhidow/quest-sideloader-linux/issues\">https://github.com/whitewhidow/quest-sideloader-linux/issues</a>\nor find me at t.me/whitewhidow_q2_working\n\nAnd i will gladly assist you!"
      zenity --info --width=800 --text="<b><u>The sideloading process has finished, please inspect the output in the terminal!</u></b>\n\n$ISSUETEXT"
      echo -e "\nThe sideloading process has finished, please inspect the output above for any errors."
      echo -e "\n$ISSUETEXT"
      echo -e ''
      read -p "Press enter to sideload another app. or CTRL+C to close the sideloader."
      continue
    else
      echo -ne ''
    fi

  else
      cd "$SELECTION" 2>/dev/null && echo "cd to $SELECTION" || zenity --warning --width=800 --text="$SELECTION is not a valid APK or valid directory"

  fi
done

exit 0
