#!/bin/bash
source sideloader-config

while test $# -gt 0; do
  case "$1" in
    --askpackage)
      ASKPACKAGE=1
      shift
      ;;
    --packagename*)
      PACKAGENAME=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    --res*)
      RES=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    *)
      break
      ;;
  esac
done


clearLog
deviceCheck
if [ $ASKPACKAGE ]; then
  while [ -z $PACKAGENAME ] && [ -z $CI ]; do
    PACKAGENAME=$(dialog --title "Packagename" --inputbox "Please enter a packagename:" 0 0 --output-fd 1)
  done
fi



if [ -z $PACKAGENAME ]; then
  [ -z $CI ] && OLDRES=$($ADB shell getprop debug.oculus.textureWidth)
  [ -z $CI ] && [ "$OLDRES" != "" ] && ok "Current global texturesize (setprop) detected as $OLDRES x $OLDRES"
  [ -z $CI ] && [ "$OLDRES" == "" ] && ok "Current global texturesize (setprop) not set"

fi

if [ ! -z $PACKAGENAME ]; then
  [ -z $CI ] && OLDRES=$($ADB shell get global texture_size_$PACKAGENAME)
  [ -z $CI ] && [ "$OLDRES" != "" ] && ok "$PACKAGENAME texturesize (putglobal) detected as $OLDRES x $OLDRES"
  [ -z $CI ] && [ "$OLDRES" == "" ] && ok "$PACKAGENAME texturesize (putglobal) not set"

fi






while [[ -z $RES ]] && [ -z $CI ]; do
  RES=$(dialog --default-item "$OLDRES" --menu "Please choose a resolution:" 0 0 0 "1024" "1024" "1208" "1208" "1536" "1536" "2048" "2048" "2560" "2560" "3072" "3072" --output-fd 1)
done








if [ -z $PACKAGENAME ]; then
  $ADB shell setprop debug.oculus.textureHeight $RES
  $ADB shell setprop debug.oculus.textureWidth $RES
  ok "Current global refreshRate (setprop) changed to \"$RES\""
fi



if [ ! -z $PACKAGENAME ]; then
  $ADB shell settings put global texture_size_$PACKAGENAME $RES
  ok "$PACKAGENAME resolution changed to $RES x $RES"
fi

dialogLog