#!/bin/bash
source sideloader-config
while test $# -gt 0; do
  case "$1" in
    --nogui)
      NOGUIFLAG=--nogui
      NOGUI=1
      shift
      ;;
    *)
      break
      ;;
  esac
done


versionCheck
packageCheck

wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
clear
intro
sleep 1
clear

#deviceCheck

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "https://github.com/whitewhidow/quest-sideloader-linux" \
    --title "Sideloader Toolkit Main Menu" \
    --clear \
    --no-tags \
    --exit-label "Close" \
    --cancel-label "Exit" \
    --menu "$VERSIONCOMPLAINT Please select:" $HEIGHT $WIDTH 20 \
    "00" "Mount cloud drive                                                                           " \
    "05" "Check cloud drive for updated versions                                                      " \
    "15" "Browse and sideload apps                                                           " \
    "20" "Switch on wireless ADB                                                                      " \
    "30" "Change global username                                                                      " \
    "40" "Change apk specific username (crack only)                                                   " \
    "50" "Change global refresh rate                                                                  " \
    "60" "Change apk specific refresh rate (crack only)                                               " \
    "70" "Change global resolution                                                                    " \
    "80" "Change apk specific resolution (crack only)                                                 " \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      #echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    00 )
      clear
      sideload-mount mount
      ;;
    05 )
      clear
      sideload-check-updates
      ;;
    10 )
      clear
      sideload-browser
      exit
      ;;
    15 )
      clear
      sideload-browser --nogui
      ;;
    20 )
      clear
      sideload-wifi
      ;;
    30 )
      clear
      sideload-change-username
      ;;
    40 )
      clear
      sideload-change-username --askpackage
      ;;
    50 )
      clear
      sideload-change-rate
      ;;
    60 )
      clear
      sideload-change-rate --askpackage
      ;;
    70 )
      clear
      sideload-change-res
      ;;
    80 )
      clear
      sideload-change-res --askpackage
      ;;
    2 )
      result=$(df -h)
      display_result "Disk Space"
      ;;
    3 )
      if [[ $(id -u) -eq 0 ]]; then
        result=$(du -sh /home/* 2> /dev/null)
        display_result "Home Space Utilization (All Users)"
      else
        result=$(du -sh $HOME 2> /dev/null)
        display_result "Home Space Utilization ($USER)"
      fi
      ;;
  esac
done