#!/bin/bash
source sideloader-config

if [ ${EUID:-$(id -u)} -eq 0 ]; then
	echo "PLEASE DO NOT RUN THIS SCRIPT USING ROOT"
	exit
fi


echo 	"Checking rclone installation."
if ! command -v rclone &> /dev/null; then
  echo "Rclone not found."
  echo "Downloading and installing rclone. (requires sudo)"
  (curl --silent https://rclone.org/install.sh | sudo bash > /dev/null) && echo "Rclone installed"
  if [ $OSTYPE == "mac" ]; then
    brew install rclone
  fi
else
  echo "Rclone installation found."
fi
if ! command -v rclone &> /dev/null; then
	failed "Rclone could not be installed ?"
else
 	echo "Rclone installed at $(which rclone)"
 	RCLONEINSTALLED=true
fi


echo -e "\nMount cloud-config.\n"

CLOC="/tmp/c"
KLOC="/tmp/k"
curl --silent https://raw.githubusercontent.com/whitewhidow/quest-sideloader-linux/main/extras/c -o "$CLOC"  > /dev/null
curl --silent https://raw.githubusercontent.com/whitewhidow/quest-sideloader-linux/main/extras/k -o "$KLOC"  > /dev/null
cr=`echo $'\n.'`
cr=${cr%.}
C=$(cat $CLOC | base64 --decode)
k=$(cat $KLOC | base64 --decode)
C=$(echo "${C/XXX/$KLOC}" )
$(echo "$C" > $CLOC)
$(echo "$k" > $KLOC)


sleep 1


if [ $(rclone --config=$CLOC listremotes | wc -l) != "1" ]; then
	echo -e "\nERROR\n\nSomething is wrong, we cannot seem to find the remote.\nif you report this at github.com/whitewhidow/quest-sideloader-linux and include the logs generated above, I will be happy to help\n\n"
	read -p "$cr$cr Press [ENTER] to continue. $cr$cr" < "$(tty 0>&2)"
	exit 1
else
  echo -e "\n\nMount-config detected successfully: $(rclone --config=$CLOC listremotes)\n\n"
fi

if [ $# -eq 0 ]; then
	#echo "Starting Rclone and gui"

	
	rclone rcd --rc-web-gui --rc-no-auth --config=$CLOC --rc-addr :0 & > /dev/null
	PID=$!
	sleep 1
	echo -e "\n\n"
	read -p "$cr$cr     Rclone-web-gui ($!) is now serving, $cr$cr     press [ENTER] to stop it gracefully. $cr$cr" < "$(tty 0>&2)"
	killall rclone 2> /dev/null
	rm --force $CLOC
	rm --force $KLOC
else
  #has path
	fusermount -uz $MNTLOC 2> /dev/null
	umount $MNTLOC 2> /dev/null
	rm -r $MNTLOC  > /dev/null 2> /dev/null
	mkdir -p $MNTLOC  > /dev/null
	#sudo chmod 777 $MNTLOC
	REM=$(rclone --config=$CLOC listremotes)







  rclone $2 -vv --no-modtime --read-only --config=$CLOC $REM $MNTLOC & > /dev/null
	#rclone mount --daemon --no-modtime --read-only --config=$CLOC $REM $MNTLOC

  #[ ! -z $CI ] && echo "::debug::Quiting early because of CI" && exit 0

	
	## is NOT ? fired by gui
	if [ $# -lt 1 ]; then
	  rclone mount -vv --no-modtime --read-only --config=$CLOC $REM $MNTLOC & > /dev/null
	  FOLDER="$MNTLOC"
	    
	  x=1
		while [ $x -le 10 ] && [ -z $MOUNTSUCCESS ]
		do
		  echo "Checking if drive is mounted (attempt $x/10)"
		  sleep 3
		  x=$(( $x + 1 ))
		  if [ "$(ls -A $FOLDER)" ]; then
		  	MOUNTSUCCESS=true
		  fi
		done
		
		if [ ! -z $MOUNTSUCCESS ]; then
		  echo -e "\n\n Drive now mounted at: $MNTLOC ($(ls $FOLDER | wc -l) folders available)\n\n"
		else
		  echo -e "\nERROR\n\nSomething is wrong, the folder seems to return as empty.\nIf you post the output of the terminal window to www.github.com/whitewhidow/quest-sideloader-linux, I will be happy to help."
		  read -p "$cr$cr     press [ENTER] to quit. $cr$cr" < "$(tty 0>&2)"
		  exit 1
		fi

	fi
	

fi
#clear
