# This is a basic workflow to help you get started with Actions

name: CI-LINUX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run install
        run: $GITHUB_WORKSPACE/install local
      - name: Run sideload-mount
        run: sideload-mount mount
      - name: Run sideload-browser
        run: sideload-browser
      - name: Run local sideload
        run: cd extras && sideload
      - name: Run remote sideload
        run: cd /tmp/mnt && cd "Little Witch Academia - VR Broom Racing v1.0.1-639" && /usr/local/bin/sideload "Little Witch Academia VR [v1.0.1-639].apk"
      - name: check-updates
        run: sideload-check-updates


      #- name: Run sideload
      #  run: cd extras && sideload
      #- name: Run sideload-browser
      #  run: sideload-browser
      #- name: Run ww-mount
      #  run: whitewhidow-mount /tmp/mnt
      #- name: Run sideload
      #  run: cd /tmp/mnt && cd "$(ls -d */|head -n 1)" && sideload